# Generated by Django 5.1.5 on 2025-03-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('beekeeper', 'Apicultor')], default='admin', max_length=15, verbose_name='Rol'),
        ),
    ]
