# Generated by Django 5.1.5 on 2025-03-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('Active', 'Activo'), ('Deactivate', 'Desactivo')], default='Active', max_length=10),
        ),
    ]
