# Generated by Django 5.1.5 on 2025-03-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_conditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherconditions',
            name='text',
            field=models.TextField(),
        ),
    ]
