# Generated by Django 5.1.5 on 2025-02-25 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hive_management', '0001_initial'),
        ('weather_conditions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beehive',
            name='beekeeper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beehive',
            name='id_weather_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_conditions.weatherconditions'),
        ),
    ]
