# Generated by Django 5.1.5 on 2025-03-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beehive',
            name='observations',
            field=models.TextField(),
        ),
    ]
