# Generated by Django 5.1.5 on 2025-02-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_date', models.DateTimeField()),
                ('queen_observations', models.CharField(max_length=50)),
                ('food_observations', models.CharField(max_length=50)),
                ('general_observations', models.CharField(max_length=90)),
            ],
        ),
    ]
