# Generated by Django 5.1.5 on 2025-03-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beehive_monitoring', '0003_alter_monitoring_beekeeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='food_observations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='general_observations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='queen_observations',
            field=models.TextField(),
        ),
    ]
