# Generated by Django 5.1.5 on 2025-02-25 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='harvesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(default=django.utils.timezone.now)),
                ('honey_production', models.FloatField()),
                ('pollen_production', models.FloatField()),
            ],
        ),
    ]
